<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Add an additive, stable reference key without replacing V1's composite
     * primary key of (appointment_id, service_id).
     */
    public function up(): void
    {
        DB::statement('ALTER TABLE appointment_services ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY');
        DB::statement('ALTER TABLE appointment_services ADD CONSTRAINT appointment_services_id_unique UNIQUE (id)');
    }

    public function down(): void
    {
        DB::statement('ALTER TABLE appointment_services DROP CONSTRAINT IF EXISTS appointment_services_id_unique');
        DB::statement('ALTER TABLE appointment_services DROP COLUMN IF EXISTS id');
    }
};
